swagger: "2.0"
info:
  version: "1.0.0"
  title: User API
  description: API for retrieving user data
host: localhost:9091
basePath: /v1
schemes:
  - http
paths:
  /users:
    get:
      summary: Get Users
      description: Retrieve a list of users with optional filtering.
      produces:
        - application/json
      parameters:
        - name: email
          in: query
          description: Filter users by email
          required: false
          type: string
      responses:
        200:
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        400:
          description: Invalid parameter
        500:
          description: Internal server error
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string