// Code generated by go-swagger; DO NOT EDIT.

// Package restapi User API
//
//	API for retrieving user data
//	Schemes:
//	  http
//	Host: localhost:9091
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
