version: '3.8'
name: altos
services:
  altos-postgres:
    restart: always
    build: ./database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5436:5432'
  swagger:
    restart: always
    build: ./swagger
    ports:
      - 9999:9999

volumes:
  alto-postgres:
    driver: local